#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagingApp.BLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AutoSMS")]
	public partial class AutoSMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_log(tb_log instance);
    partial void Updatetb_log(tb_log instance);
    partial void Deletetb_log(tb_log instance);
    partial void Inserttb_network_code(tb_network_code instance);
    partial void Updatetb_network_code(tb_network_code instance);
    partial void Deletetb_network_code(tb_network_code instance);
    partial void Inserttb_login_user(tb_login_user instance);
    partial void Updatetb_login_user(tb_login_user instance);
    partial void Deletetb_login_user(tb_login_user instance);
    partial void Inserttb_user(tb_user instance);
    partial void Updatetb_user(tb_user instance);
    partial void Deletetb_user(tb_user instance);
    partial void Inserttb_gateway_config(tb_gateway_config instance);
    partial void Updatetb_gateway_config(tb_gateway_config instance);
    partial void Deletetb_gateway_config(tb_gateway_config instance);
    #endregion
		
		public AutoSMSDataContext() : 
				base(global::MessagingApp.Properties.Settings.Default.AutoSMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AutoSMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoSMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoSMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoSMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_log> tb_logs
		{
			get
			{
				return this.GetTable<tb_log>();
			}
		}
		
		public System.Data.Linq.Table<tb_network_code> tb_network_codes
		{
			get
			{
				return this.GetTable<tb_network_code>();
			}
		}
		
		public System.Data.Linq.Table<tb_client_config> tb_client_configs
		{
			get
			{
				return this.GetTable<tb_client_config>();
			}
		}
		
		public System.Data.Linq.Table<tb_login_user> tb_login_users
		{
			get
			{
				return this.GetTable<tb_login_user>();
			}
		}
		
		public System.Data.Linq.Table<tb_user> tb_users
		{
			get
			{
				return this.GetTable<tb_user>();
			}
		}
		
		public System.Data.Linq.Table<tb_gateway_config> tb_gateway_configs
		{
			get
			{
				return this.GetTable<tb_gateway_config>();
			}
		}
		
		public System.Data.Linq.Table<vwLog> vwLogs
		{
			get
			{
				return this.GetTable<vwLog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_logs")]
	public partial class tb_log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _logger_id;
		
		private System.Nullable<int> _user_id;
		
		private System.Nullable<bool> _isFromServer;
		
		private string _sender_mobile_number;
		
		private System.Nullable<bool> _isCommandSent;
		
		private string _msg_text;
		
		private System.Nullable<bool> _isUserReplied;
		
		private System.Nullable<System.DateTime> _to_command_time_stamp;
		
		private System.Nullable<System.DateTime> _to_user_time_stamp;
		
		private EntityRef<tb_user> _tb_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlogger_idChanging(int value);
    partial void Onlogger_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void OnisFromServerChanging(System.Nullable<bool> value);
    partial void OnisFromServerChanged();
    partial void Onsender_mobile_numberChanging(string value);
    partial void Onsender_mobile_numberChanged();
    partial void OnisCommandSentChanging(System.Nullable<bool> value);
    partial void OnisCommandSentChanged();
    partial void Onmsg_textChanging(string value);
    partial void Onmsg_textChanged();
    partial void OnisUserRepliedChanging(System.Nullable<bool> value);
    partial void OnisUserRepliedChanged();
    partial void Onto_command_time_stampChanging(System.Nullable<System.DateTime> value);
    partial void Onto_command_time_stampChanged();
    partial void Onto_user_time_stampChanging(System.Nullable<System.DateTime> value);
    partial void Onto_user_time_stampChanged();
    #endregion
		
		public tb_log()
		{
			this._tb_user = default(EntityRef<tb_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logger_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int logger_id
		{
			get
			{
				return this._logger_id;
			}
			set
			{
				if ((this._logger_id != value))
				{
					this.Onlogger_idChanging(value);
					this.SendPropertyChanging();
					this._logger_id = value;
					this.SendPropertyChanged("logger_id");
					this.Onlogger_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._tb_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isFromServer", DbType="Bit")]
		public System.Nullable<bool> isFromServer
		{
			get
			{
				return this._isFromServer;
			}
			set
			{
				if ((this._isFromServer != value))
				{
					this.OnisFromServerChanging(value);
					this.SendPropertyChanging();
					this._isFromServer = value;
					this.SendPropertyChanged("isFromServer");
					this.OnisFromServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sender_mobile_number", DbType="NVarChar(50)")]
		public string sender_mobile_number
		{
			get
			{
				return this._sender_mobile_number;
			}
			set
			{
				if ((this._sender_mobile_number != value))
				{
					this.Onsender_mobile_numberChanging(value);
					this.SendPropertyChanging();
					this._sender_mobile_number = value;
					this.SendPropertyChanged("sender_mobile_number");
					this.Onsender_mobile_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isCommandSent", DbType="Bit")]
		public System.Nullable<bool> isCommandSent
		{
			get
			{
				return this._isCommandSent;
			}
			set
			{
				if ((this._isCommandSent != value))
				{
					this.OnisCommandSentChanging(value);
					this.SendPropertyChanging();
					this._isCommandSent = value;
					this.SendPropertyChanged("isCommandSent");
					this.OnisCommandSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg_text", DbType="NVarChar(MAX)")]
		public string msg_text
		{
			get
			{
				return this._msg_text;
			}
			set
			{
				if ((this._msg_text != value))
				{
					this.Onmsg_textChanging(value);
					this.SendPropertyChanging();
					this._msg_text = value;
					this.SendPropertyChanged("msg_text");
					this.Onmsg_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isUserReplied", DbType="Bit")]
		public System.Nullable<bool> isUserReplied
		{
			get
			{
				return this._isUserReplied;
			}
			set
			{
				if ((this._isUserReplied != value))
				{
					this.OnisUserRepliedChanging(value);
					this.SendPropertyChanging();
					this._isUserReplied = value;
					this.SendPropertyChanged("isUserReplied");
					this.OnisUserRepliedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_to_command_time_stamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> to_command_time_stamp
		{
			get
			{
				return this._to_command_time_stamp;
			}
			set
			{
				if ((this._to_command_time_stamp != value))
				{
					this.Onto_command_time_stampChanging(value);
					this.SendPropertyChanging();
					this._to_command_time_stamp = value;
					this.SendPropertyChanged("to_command_time_stamp");
					this.Onto_command_time_stampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_to_user_time_stamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> to_user_time_stamp
		{
			get
			{
				return this._to_user_time_stamp;
			}
			set
			{
				if ((this._to_user_time_stamp != value))
				{
					this.Onto_user_time_stampChanging(value);
					this.SendPropertyChanging();
					this._to_user_time_stamp = value;
					this.SendPropertyChanged("to_user_time_stamp");
					this.Onto_user_time_stampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_log", Storage="_tb_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public tb_user tb_user
		{
			get
			{
				return this._tb_user.Entity;
			}
			set
			{
				tb_user previousValue = this._tb_user.Entity;
				if (((previousValue != value) 
							|| (this._tb_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_user.Entity = null;
						previousValue.tb_logs.Remove(this);
					}
					this._tb_user.Entity = value;
					if ((value != null))
					{
						value.tb_logs.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_network_codes")]
	public partial class tb_network_code : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private string _network;
		
		private string _code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void OnnetworkChanging(string value);
    partial void OnnetworkChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    #endregion
		
		public tb_network_code()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_network", DbType="NVarChar(50)")]
		public string network
		{
			get
			{
				return this._network;
			}
			set
			{
				if ((this._network != value))
				{
					this.OnnetworkChanging(value);
					this.SendPropertyChanging();
					this._network = value;
					this.SendPropertyChanged("network");
					this.OnnetworkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(50)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_client_config")]
	public partial class tb_client_config
	{
		
		private string _Client;
		
		private string _username;
		
		private string _password;
		
		private string _port;
		
		public tb_client_config()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="NVarChar(50)")]
		public string Client
		{
			get
			{
				return this._Client;
			}
			set
			{
				if ((this._Client != value))
				{
					this._Client = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_port", DbType="NVarChar(50)")]
		public string port
		{
			get
			{
				return this._port;
			}
			set
			{
				if ((this._port != value))
				{
					this._port = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_login_user")]
	public partial class tb_login_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uid;
		
		private string _user_name;
		
		private string _password;
		
		private System.Data.Linq.Binary _creation_date;
		
		private System.Nullable<bool> _isActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(int value);
    partial void OnuidChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Oncreation_dateChanging(System.Data.Linq.Binary value);
    partial void Oncreation_dateChanged();
    partial void OnisActiveChanging(System.Nullable<bool> value);
    partial void OnisActiveChanged();
    #endregion
		
		public tb_login_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creation_date", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary creation_date
		{
			get
			{
				return this._creation_date;
			}
			set
			{
				if ((this._creation_date != value))
				{
					this.Oncreation_dateChanging(value);
					this.SendPropertyChanging();
					this._creation_date = value;
					this.SendPropertyChanged("creation_date");
					this.Oncreation_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_users")]
	public partial class tb_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _name;
		
		private string _mobile_number;
		
		private System.Nullable<bool> _isActive;
		
		private string _section;
		
		private EntitySet<tb_log> _tb_logs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onmobile_numberChanging(string value);
    partial void Onmobile_numberChanged();
    partial void OnisActiveChanging(System.Nullable<bool> value);
    partial void OnisActiveChanged();
    partial void OnsectionChanging(string value);
    partial void OnsectionChanged();
    #endregion
		
		public tb_user()
		{
			this._tb_logs = new EntitySet<tb_log>(new Action<tb_log>(this.attach_tb_logs), new Action<tb_log>(this.detach_tb_logs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile_number", DbType="NVarChar(50)")]
		public string mobile_number
		{
			get
			{
				return this._mobile_number;
			}
			set
			{
				if ((this._mobile_number != value))
				{
					this.Onmobile_numberChanging(value);
					this.SendPropertyChanging();
					this._mobile_number = value;
					this.SendPropertyChanged("mobile_number");
					this.Onmobile_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit")]
		public System.Nullable<bool> isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_section", DbType="NVarChar(50)")]
		public string section
		{
			get
			{
				return this._section;
			}
			set
			{
				if ((this._section != value))
				{
					this.OnsectionChanging(value);
					this.SendPropertyChanging();
					this._section = value;
					this.SendPropertyChanged("section");
					this.OnsectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_log", Storage="_tb_logs", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<tb_log> tb_logs
		{
			get
			{
				return this._tb_logs;
			}
			set
			{
				this._tb_logs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_logs(tb_log entity)
		{
			this.SendPropertyChanging();
			entity.tb_user = this;
		}
		
		private void detach_tb_logs(tb_log entity)
		{
			this.SendPropertyChanging();
			entity.tb_user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_gateway_config")]
	public partial class tb_gateway_config : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tb_id;
		
		private string _ipaddress;
		
		private string _port;
		
		private string _username;
		
		private string _password;
		
		private string _tsc1;
		
		private string _tsc2;
		
		private string _t15;
		
		private string _welcomemsg;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontb_idChanging(int value);
    partial void Ontb_idChanged();
    partial void OnipaddressChanging(string value);
    partial void OnipaddressChanged();
    partial void OnportChanging(string value);
    partial void OnportChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Ontsc1Changing(string value);
    partial void Ontsc1Changed();
    partial void Ontsc2Changing(string value);
    partial void Ontsc2Changed();
    partial void Ont15Changing(string value);
    partial void Ont15Changed();
    partial void OnwelcomemsgChanging(string value);
    partial void OnwelcomemsgChanged();
    #endregion
		
		public tb_gateway_config()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tb_id
		{
			get
			{
				return this._tb_id;
			}
			set
			{
				if ((this._tb_id != value))
				{
					this.Ontb_idChanging(value);
					this.SendPropertyChanging();
					this._tb_id = value;
					this.SendPropertyChanged("tb_id");
					this.Ontb_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ipaddress", DbType="NVarChar(50)")]
		public string ipaddress
		{
			get
			{
				return this._ipaddress;
			}
			set
			{
				if ((this._ipaddress != value))
				{
					this.OnipaddressChanging(value);
					this.SendPropertyChanging();
					this._ipaddress = value;
					this.SendPropertyChanged("ipaddress");
					this.OnipaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_port", DbType="NVarChar(50)")]
		public string port
		{
			get
			{
				return this._port;
			}
			set
			{
				if ((this._port != value))
				{
					this.OnportChanging(value);
					this.SendPropertyChanging();
					this._port = value;
					this.SendPropertyChanged("port");
					this.OnportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tsc1", DbType="NVarChar(50)")]
		public string tsc1
		{
			get
			{
				return this._tsc1;
			}
			set
			{
				if ((this._tsc1 != value))
				{
					this.Ontsc1Changing(value);
					this.SendPropertyChanging();
					this._tsc1 = value;
					this.SendPropertyChanged("tsc1");
					this.Ontsc1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tsc2", DbType="NVarChar(50)")]
		public string tsc2
		{
			get
			{
				return this._tsc2;
			}
			set
			{
				if ((this._tsc2 != value))
				{
					this.Ontsc2Changing(value);
					this.SendPropertyChanging();
					this._tsc2 = value;
					this.SendPropertyChanged("tsc2");
					this.Ontsc2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t15", DbType="NVarChar(50)")]
		public string t15
		{
			get
			{
				return this._t15;
			}
			set
			{
				if ((this._t15 != value))
				{
					this.Ont15Changing(value);
					this.SendPropertyChanging();
					this._t15 = value;
					this.SendPropertyChanged("t15");
					this.Ont15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_welcomemsg", DbType="NVarChar(MAX)")]
		public string welcomemsg
		{
			get
			{
				return this._welcomemsg;
			}
			set
			{
				if ((this._welcomemsg != value))
				{
					this.OnwelcomemsgChanging(value);
					this.SendPropertyChanging();
					this._welcomemsg = value;
					this.SendPropertyChanged("welcomemsg");
					this.OnwelcomemsgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwLogs")]
	public partial class vwLog
	{
		
		private int _Log_ID;
		
		private string _Name;
		
		private string _Mobile_Number;
		
		private string _Command;
		
		private System.Nullable<System.DateTime> _Time;
		
		public vwLog()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_ID", DbType="Int NOT NULL")]
		public int Log_ID
		{
			get
			{
				return this._Log_ID;
			}
			set
			{
				if ((this._Log_ID != value))
				{
					this._Log_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile_Number", DbType="NVarChar(50)")]
		public string Mobile_Number
		{
			get
			{
				return this._Mobile_Number;
			}
			set
			{
				if ((this._Mobile_Number != value))
				{
					this._Mobile_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Command", DbType="NVarChar(MAX)")]
		public string Command
		{
			get
			{
				return this._Command;
			}
			set
			{
				if ((this._Command != value))
				{
					this._Command = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this._Time = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
